app = "good-blast-real"
primary_region = "otp"

[build]
  [build.args]
    GO_VERSION = "1.20"

[env]
  PORT = "8080"
  # If you want to reference Redis from your code, you can set these too:
  # REDIS_HOST = "localhost"
  # REDIS_PORT = "6379"[env]
  REDIS_HOST = "localhost"
  REDIS_PORT = "6379"
  DYNAMODB_REGION = "eu-north-1" # Replace with your actual AWS region
  USERS_TABLE = "Users" # Replace with your actual Users table name
  TOURNAMENTS_TABLE = "Tournaments" # Replace with your actual Tournaments table name
  TOURNAMENT_ENTRIES_TABLE = "TournamentEntries" # Replace with your actual TournamentEntries table name

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "redis_data"
  destination = "/data"